// Generated by dts-bundle v0.7.3

declare module 'slate-plain-serializer' {
    const _default: {
        deserialize: (string: any, options?: {}) => any;
        serialize(value: any): any
    };
    export default _default;
}

