// Generated by dts-bundle v0.7.3

declare module "slate-auto-replace" {
  /**
   * A Slate plugin to automatically replace a block when a string of matching
   * text is typed.
   *
   * @param {Object} opts
   * @return {Object}
   */
  function AutoReplace(opts?: {}): {
    onKeyDown(event: any, change: any, editor: any): any;
  };
  export default AutoReplace;
}
