// Generated by dts-bundle v0.7.3

declare module "slate-soft-break" {
  /**
   * A Slate plugin to add soft breaks on return.
   *
   * @param {Object} options
   *   @property {Array} onlyIn
   *   @property {Array} ignoreIn
   * @return {Object}
   */
  function SoftBreak(options?: {}): {
    onKeyDown(event: any, change: any): any;
  };
  export default SoftBreak;
}
