// Generated by dts-bundle v0.7.3

declare module "slate-drop-or-paste-images" {
  /**
   * Insert images on drop or paste.
   *
   * @param {Object} options
   *   @property {Function} insertImage
   *   @property {Array} extensions (optional)
   * @return {Object} plugin
   */
  function DropOrPasteImages(options?: {}): {
    onDrop(event: any, change: any, editor: any): boolean;
    onPaste(event: any, change: any, editor: any): boolean;
  };
  export default DropOrPasteImages;
}
