// Generated by dts-bundle v0.7.3

declare module 'slate-base64-serializer' {
    const _default: {
        deserialize: (string: any, options: any) => any;
        deserializeNode: (string: any, options: any) => any;
        serialize: (state: any, options: any) => string;
        serializeNode: (node: any, options: any) => string;
    };
    export default _default;
}

