// Generated by dts-bundle v0.7.3

declare module 'slate-base64-serializer' {
    const _default: {
        deserialize(string: any, options: any): any
        deserializeNode(string: any, options: any): any
        serialize(value: any, options: any): any
        serializeNode(node: any, options: any): any
    };
    export default _default;
}

