// Generated by dts-bundle v0.7.3

declare module 'slate-simulator' {
    /**
        * Simulator.
        *
        * @type {Simulator}
        */
    class Simulator {
            /**
                * Create a new `Simulator` with `plugins` and an initial `value`.
                *
                * @param {Object} attrs
                */
            constructor(props: any);
    }
    export default Simulator;
}

