// Generated by dts-bundle v0.7.3

declare module 'slate-simulator' {
    /**
        * Simulator.
        *
        * @type {Simulator}
        */
    class Simulator {
            /**
                * Create a new `Simulator` with `plugins` and an initial `state`.
                *
                * @param {Object} attrs
                */
            constructor({plugins, state}: {
                    plugins: any;
                    state: any;
            });
    }
    export default Simulator;
}

