// Generated by dts-bundle v0.7.3

declare module 'slate-hyperscript' {
    /**
      * Create a Slate hyperscript function with `options`.
      *
      * @param {Object} options
      * @return {Function}
      */
    function createHyperscript(options?: {}): (tagName: any, attributes: any, ...children: any[]) => any;
    const _default: (tagName: any, attributes: any, ...children: any[]) => any;
    export default _default;
    export { createHyperscript };
}

