// Generated by dts-bundle v0.7.3

declare module 'slate-dev-logger' {
    const _default: {
        deprecate: (version: any, message: any, ...args: any[]) => void;
        error: (message: any, ...args: any[]) => void;
        warn: (message: any, ...args: any[]) => void;
    };
    export default _default;
}

