// Generated by dts-bundle v0.7.3

declare module "slate-paste-linkify" {
  /**
   * A Slate plugin to add soft breaks on return.
   *
   * @param {Object} options
   *   @property {String} type
   *   @property {String} hrefProperty
   *   @property {String} collapseTo
   * @return {Object}
   */
  function PasteLinkify(options?: {}): {
    onPaste(event: any, change: any): any;
  };
  export default PasteLinkify;
}
