// Generated by dts-bundle v0.7.3

declare module "slate-prop-types" {
  /**
   * Prop type checkers.
   *
   * @type {Object}
   */
  const Types: {
    block: (...args: any[]) => any;
    blocks: (...args: any[]) => any;
    change: (...args: any[]) => any;
    character: (...args: any[]) => any;
    characters: (...args: any[]) => any;
    data: (...args: any[]) => any;
    document: (...args: any[]) => any;
    history: (...args: any[]) => any;
    inline: (...args: any[]) => any;
    inlines: (...args: any[]) => any;
    leaf: (...args: any[]) => any;
    leaves: (...args: any[]) => any;
    mark: (...args: any[]) => any;
    marks: (...args: any[]) => any;
    node: (...args: any[]) => any;
    nodes: (...args: any[]) => any;
    range: (...args: any[]) => any;
    ranges: (...args: any[]) => any;
    schema: (...args: any[]) => any;
    stack: (...args: any[]) => any;
    value: (...args: any[]) => any;
    text: (...args: any[]) => any;
    texts: (...args: any[]) => any;
  };
  export default Types;
}
